models_to_train: [
    # "SimplePPModel",
    # "TransformerOnly",
    # "EEGConformer",
    # "PPModel",
    # "EEGTransformerEmb",
    # "GraphFormer",
    "SimpleGraphFormer",
    # "ShallowFBCSPNet",
    # "SimpleShallowNet",
    # "SimpleConformer",
    # "ConformerCopy",
  ]
dataset_list: [
    # "BCI_2B_CONTINUOUS",
    "BCI_2A_CONTINUOUS",
    # "BCI_2B_PERMUTED",
    # "BCI_2A_PERMUTED",
    # "SIMPLE_BCI_2A_PERMUTED",
    # "SIMPLE_BCI_2B_PERMUTED",
  ]
test: True

train_params:
  epochs: 100
  batch_size: 64
  lr: 0.0001
  classes: 4
  weight_decay: 0.0001
  wandb_logging: True
  project_name: "FINAL REPORT ALL SUBJECTS"
  run_name: "SimpleConformer + ConformerCopy with new classificationhead"

models:
  EEGConformer:
    n_chans: [22]
    add_log_softmax: [False]
    final_fc_length: ["auto"]
  SimplePPModel:
    nhead: [2]
    expansion: [4]
    dropout: [0.5]
    emb_size: [10]
  PPModel:
    nhead: [2]
    depth: [2]
    emb_size: [22]
    expansion: [4]
    dropout: [0.7]
  TransformerOnly:
    nhead: [2]
    depth: [2]
    emb_size: [22]
    expansion: [4]
    dropout: [0.7]
  EEGTransformerEmb:
    nhead: [2]
    depth: [2]
    emb_size: [20]
    expansion: [4]
    dropout: [0.7]
  ShallowFBCSPNet:
    n_chans: [22]
    final_conv_length: ["auto"]
  ConformerCopy:
    in_channels: [22]
    num_kernels: [40]
    nhead: [10]
    pool_size: [75]
    dropout: [0.6]
  SimpleGraphFormer:
    nhead: [2]
    depth: [2]
    emb_size: [22]
    num_blocks: [1, 3, 5]
    expansion: [4]
    dropout: [0.5]
    K: [1, 2, 3, 5, 9]
    avg_pool_kernel: [5, 15]
    avg_pool_stride: [3, 5]
  GraphFormer:
    nhead: [2]
    depth: [2]
    emb_size: [22]
    expansion: [4]
    dropout: [0.6]
    K: [2, 3, 7]
  SimpleShallowNet:
    dropout: [0.4]
    in_channels: [22]
    num_kernels: [40]
    kernel_size: [25]
    pool_size: [75]
  SimpleConformer:
    in_channels: [22]
    num_kernels: [40]
    nhead: [10]
    pool_size: [75]
    dropout: [0.6]
datasets:
  BCI_2A_CONTINUOUS:
  BCI_2B_CONTINUOUS:
  BCI_2A_PERMUTED:
    window_size: [5]
    stride: [7]
  BCI_2B_PERMUTED:
    window_size: [5]
    stride: [7]
  SIMPLE_BCI_2A_PERMUTED:
    window_size: [7]
    stride: [11]
  SIMPLE_BCI_2B_PERMUTED:
    window_size: [7]
    stride: [11]
