models_to_train: ["EEGTransformer"]
dataset: "BNCI_LEFT_RIGHT_NEW_PE"

train_params:
  epochs: 900
  batch_size: 64
  lr: 0.0001
  classes: 2
  weight_decay: 0.0001

models:
  EEGConformer:
    n_outputs: [2]
    n_chans: [22]
    add_log_softmax: [False]
    final_fc_length: ["auto"]
  VanillaTransformer:
    num_electrodes: [22]
    heads: [8]
    num_classes: [2]
    hid_channels: [256]
    mlp_channels: [128]
  BasicTransformer:
    n_channels: [22]
    dropout: [0.5]
  Transformer:
    d_model: [100]
    n_head: [2]
    ffn_hidden: [128]
    n_layers: [2]
    n_channels: [22]
    n_classes: [2]
    drop_prob: [0.5, 0.8]
  EEGTransformer:
    nhead: [2]
    num_classes: [2]
    depth: [2]
    emb_size: [22]
    expansion: [4]
    dropout: [0.5]
  EEGTransformerEmb:
    nhead: [2]
    num_classes: [2]
    depth: [2]
    emb_size: [22, 32, 64, 128]
    expansion: [4]
    dropout: [0.5]
datasets:
  BNCI_LEFT_RIGHT:
    window_size: [6, 7, 8, 9, 10, 11]
    stride: [9, 11, 13]
    strategy: ["permute"]
  BNCI_LEFT_RIGHT_CONTINUOUS:
  BNCI_LEFT_RIGHT_COMPRESSED:
    window_size: [6, 9, 11]
    stride: [9, 11]
    strategy: [None]
  BNCI_LEFT_RIGHT_NEW_PE:
    window_size: [3, 4, 6]
    stride: [1, 3, 5]
    strategy: [None]
