models_to_train: [
    "EEGTransformerFlatten",
    # "TransformerOnly",
    # "EEGConformer",
    # "EEGTransformer",
    # "EEGTransformerEmb",
    # "ConformerCopy",
    # "GraphFormer",
  ]
dataset_list: [
    # "BCI_2A_CONTINUOUS",
    # "BCI_2B_CONTINUOUS",
    # "BCI_2B_PERMUTED",
    # "BCI_2A_PERMUTED",
    "SIMPLE_BCI_2A_PERMUTED",
    "SIMPLE_BCI_2B_PERMUTED",
  ]
test: True

train_params:
  epochs: 900
  batch_size: 64
  lr: 0.0001
  classes: 4
  weight_decay: 0.0001
  wandb_logging: True
  project_name: "first test accuracy (64 batch no downsample)"

models:
  EEGConformer:
    n_chans: [22]
    add_log_softmax: [False]
    final_fc_length: ["auto"]
  EEGTransformerFlatten:
    nhead: [2]
    expansion: [4]
    dropout: [0.5]
    emb_size: [10]
  EEGTransformer:
    nhead: [2]
    depth: [2]
    emb_size: [22]
    expansion: [4]
    dropout: [0.7]
  TransformerOnly:
    nhead: [2]
    depth: [2]
    emb_size: [22]
    expansion: [4]
    dropout: [0.7]
  EEGTransformerEmb:
    nhead: [2]
    depth: [2]
    emb_size: [20]
    expansion: [4]
    dropout: [0.7]
  ConformerCopy:
    nhead: [2]
    depth: [2]
    emb_size: [20]
    expansion: [4]
    dropout: [0.7]
  GraphFormer:
    nhead: [2]
    depth: [2]
    emb_size: [20]
    expansion: [4]
    dropout: [0.5, 0.8]
    K: [2, 7]
datasets:
  BCI_2A_CONTINUOUS:
  BCI_2B_CONTINUOUS:
  BCI_2A_PERMUTED:
    window_size: [2]
    stride: [1]
  BCI_2B_PERMUTED:
    window_size: [2]
    stride: [1]
  SIMPLE_BCI_2A_PERMUTED:
    window_size: [6, 7]
    stride: [7, 11]
  SIMPLE_BCI_2B_PERMUTED:
    window_size: [7]
    stride: [11]
