models_to_train: ["EEGConformer", "Transformer"]
dataset: "BNCI_LEFT_RIGHT"

train_params:
  epochs: 400
  batch_size: 64
  lr: 0.0001
  classes: 2
  weight_decay: 0.0001

models:
  EEGConformer:
    n_outputs: [2]
    n_chans: [22]
    add_log_softmax: [False]
    final_fc_length: ["auto"]
  VanillaTransformer:
    num_electrodes: [22]
    heads: [8]
    num_classes: [2]
    hid_channels: [256]
    mlp_channels: [128]
  BasicTransformer:
    n_channels: [22]
    dropout: [0.5]
  Transformer:
    d_model: [100]
    n_head: [2]
    ffn_hidden: [128]
    n_layers: [2]
    n_channels: [22]
    n_classes: [2]
    drop_prob: [0.5, 0.8]
datasets:
  BNCI_LEFT_RIGHT:
    window_size: [5, 6, 7, 8]
    stride: [2, 3, 4, 5]
    strategy: ["permute"]
  BNCI_LEFT_RIGHT_CONTINUOUS:
