models_to_train: ["EEGConformer"]
dataset: "BNCI_LEFT_RIGHT_CONTINUOUS"

train_params:
  epochs: 1
  batch_size: 64
  lr: 0.001
  classes: 2
  weight_decay: 0.0001

models:
  EEGConformer:
    n_outputs: [2]
    n_chans: [22]
    add_log_softmax: [False]
    final_fc_length: ["auto"]
  VanillaTransformer:
    n_outputs: [2]
    n_chans: [22]
    add_log_softmax: [False]
    final_fc_length: ["auto"]

datasets:
  BNCI_LEFT_RIGHT:
    window_size: [5, 6]
    stride: [2, 3]
    strategy: ["permute"]
  BNCI_LEFT_RIGHT_CONTINUOUS:
